### ISSUE TITLE
`archinfo.arch_arm.is_arm_arch` returns `False` for AArch64

### ISSUE THREAD

**Issue by LukeSerne** [angr/archinfo#109]
## Description
The function `archinfo.arch_arm.is_arm_arch` returns `False` for `archinfo.ArchAArch64`:
```python
>>> import archinfo
>>> archinfo.arch_arm.is_arm_arch(archinfo.ArchAArch64)
False
```
The implementation of `is_arm_arch` (also) checks if the `name` string starts with `"AArch"`. However, `archinfo.ArchAArch64.name` is `"AARCH64"`. In fact, there is no arch that has a `name` that starts with `"AArch"`. As such, I assume this is a bug - either in `is_arm_arch` or in the definition of `archinfo.ArchAArch64.name`.

## Possible fix
A possible fix could be to change the implementation of `is_arm_arch` slightly to:
```python
def is_arm_arch(a):
    return a.name.startswith('ARM') or a.name.startswith('AARCH')
```

**Comment by rhelmot** [comment]
oops!!!!!

I would really rather the aarch64 arch be AArch, but it's too late for that I guess!

**Comment by rhelmot** [comment]
It looks like the above commit causes several of our tests to fail. I'm going to revert it until I have time to investigate.

**Comment by ltfish** [comment]
Hi all, I believe there is some logic in angr that relies on “AArch64 not being ARM.” I’ve been writing code with the understanding that `is_arm_arch()` is testing if the architecture is an ARM 32-bit architecture, because, obviously, AArch64 has a lot of differences than ARM 32.

**Comment by LukeSerne** [comment]
In that case, it might be better to just change the implementation to the below. It doesn't change functionality, so all tests should be unaffected, but it's not suggesting it returns `True` for AArch64. 
```python
def is_arm_arch(a):
    return a.name.startswith('ARM')
```

**Comment by rhelmot** [comment]
I've applied the recommended patch. Thanks!
