### ISSUE TITLE
Don't hardcode vex register offsets

### ISSUE THREAD

**Issue by rhelmot** [angr/archinfo#19]
We've been advised by the valgrind people that those offsets are not meant to be stable across platforms, or even across compilers. The correct solution is to have a method in pyvex that extracts the current platform's offsets from libvex (this can be via a function in pyvex_native that simply does a bunch of `offsetof` calculations) and if pyvex is available at import time, use that to populate the register fields.

This will drastically simplify the maintenance of archinfo.

**Comment by subwire** [comment]
Can I assume you mean "the offsets into the simulated register file"?
While I'm not quite clear on why those would change randomly, we'll need to make sure to tell people to use that when writing spotters against a libvex-supported architecture.  CC @Nilocunger

**Comment by rhelmot** [comment]
They absolutely can change randomly, mostly because of alignment issues - at one point there was an issue where it would change if you compiled with gcc vs clang because gcc will only align `double` types to 4 bytes by default.

**Comment by rhelmot** [comment]
For python-based lifters it's wayyyy less of a problem, and those can be hardcoded in archinfo.

**Comment by rhelmot** [comment]
I believe this is fixed!
