### ISSUE TITLE
instruction_endness not set for ArchARM & ArchAArch64

### ISSUE THREAD

**Issue by canpadawan** [angr/archinfo#29]
a comment in gymrat states:
```python
if self.arch.instruction_endness == 'Iend_LE':                           
   # This arch stores its instructions in memory endian-flipped compared to the ISA.
   # To enable natural lifter-writing, we let the user write them like in the manual, and correct for
   # endness here
```
This is useful to implement the instruction regardless of the endianness (and cover both at once):

Archinfos for arm and arm64 dont set the `instruction_endness`.

something like this would do 
```python
class ArchARM(Arch):                                                             
   def __init__(self, endness=Endness.LE):                                      
      super(ArchARM, self).__init__(endness)                                   
      self.instruction_endness = endness
```

```python
class ArchAArch64(Arch):                                                         
   def __init__(self, endness=Endness.LE):                                      
      super(ArchAArch64, self).__init__(endness)                               
      self.instruction_endness = endness
```

**Comment by zardus** [comment]
I'd prefer:

```
class Arch(**kwargs):
    def __init__(self, **kwargs):
        self.instruction_endness = kwargs.pop('instruction_endness', Endness.BE)
        # and other stuff like the above

class ArchARM(Arch):
    def __init__(self, endness=Endness.LE, **kwargs):
        super(ArchARM, self).__init__(endness=endness, **kwargs)
```

This'll allow us to override things other than just instruction endness just as easily.

**Comment by canpadawan** [comment]
IMO, it makes sense for options you want to override at instantiation.
Would a specific arch need to customize its instruction_endness at init?

**Comment by rhelmot** [comment]
The reason instruction_endness exists as a separate field from memory_endness is that some godforsaken arm chips will use big endian instructions and little endian memory accesses, or vice versa.

**Comment by canpadawan** [comment]
gotcha,
so if we want to avoid breaking the user, maybe we can go with:
```python
class Arch(**kwargs):
    def __init__(self, **kwargs):
        self.instruction_endness = kwargs.pop('instruction_endness', Endness.BE)
        # and other stuff like the above

class ArchARM(Arch):
    def __init__(self, endness=Endness.LE, instruction_endness=None, **kwargs):
        if instruction_endness is None:
            #set default safe value for instruction_endness
            instruction_endness = endness
        super(ArchARM, self).__init__(endness=endness,
                                      instruction_endness=instruction_endness,
                                      **kwargs)
```

I guess `__eq__` also needs to be modified.

What value should be used (memory_endness or instruction_endness) to configure frameworks  (capstone & co)?

I don't see the distinction in frameworks between data and instruction endness. I haven't think enough about it but I have the impression it might be relevant at least for unicorn.

If so, we should probably warn user when memory_endness!=instruction_endness that we can't take the full configuration into account?

Another issue we have is that `arch.copy()` does not really copy but calls _default [constructor.](https://github.com/angr/archinfo/blob/master/archinfo/arch.py#L162)_ 
instruction_endness and other stuff like the above won't survive copy.

**Comment by rhelmot** [comment]
right :(

unfortunately I don't know where any of the old samples we had where this actually mattered are anymore, so I can't point you to any source of ground truth. I'd be willing to accept any pull request that looks like it made sense, but maybe @zardus knows where those samples live.

**Comment by ltfish** [comment]
> What value should be used (memory_endness or instruction_endness) to configure frameworks (capstone & co)?

Capstone does not try to support as many architectures as we are trying to support, which is probably why it hasn't been an issue for them. You want to stick to `memory_endness` for now when dealing with capstone, I believe.

**Comment by ltfish** [comment]
Commit 991b3d77c59ccb14d6eee7a0e11603f618495cbe solves this issue.
