### ISSUE TITLE
New Register class - Weird ARM32-Name

### ISSUE THREAD

**Issue by AndyXan** [angr/archinfo#36]
Hello, 

the new Register-Class introduces weird ARM32-Register names, e.g. 'a1' instead of 'r0'. For AARCH64 and X64/X86 everything seems fine from my side.

Is there a particular reason for this naming scheme, or is it open for a pull-request to change this for arm32?

**Comment by rhelmot** [comment]
Take a look at the conversation on the pull request for that change.
@tyb0807 (I think that’s his nick? I can’t get autocomplete on the numbers
in my email app) thought the semantic names (e.g. a1-a4 are the argument
registers) were better defaults, and I agreed without thinking about it too
hard. If you can explain why the change is a burden I’ll switch them back.

**Comment by tyb0807** [comment]
Btw, you do have `r[0-15]` registers in `arch.registers` dict. They are considered aliases for semantic names

**Comment by tyb0807** [comment]
I do not invent the convention for semantic names. Please checkout the documentation of ARM. `a1` is also a "real machine state register" according to ARM.

For `calling_convetions.py`, I guess we should not hard-code `ARG_REGS`. It should be initialized using `argument_registers` list from `arch.ArchARM`. Regardless, you can still use `r0 -r3` if you want. What is the issue that you got with the new naming scheme?

**Comment by AndyXan** [comment]
Well it's the name for the APCS. And the "Issue" is not a big deal for any analysis, so in any case: Not a biggie. But I try to go a bit more into detail. 

I'm working on some program which requires a platform independent visualization of states and thus registers: 

![screenshot from 2018-06-13 11-00-27](https://user-images.githubusercontent.com/12801920/41342197-f3b3dbbe-6efb-11e8-8e76-8c623fcffd70.png)
![screenshot from 2018-06-13 11-01-53](https://user-images.githubusercontent.com/12801920/41342272-240a86fa-6efc-11e8-872e-5639c4118650.png)
![screenshot from 2018-06-13 11-06-26](https://user-images.githubusercontent.com/12801920/41342201-f51fb888-6efb-11e8-98b1-3ec302b7ec63.png)


The register names are not matching and disassembly view, not IDA's and not capstones. So for visualization purposes, So, above screenshots are generated from the same code. What previously was possible is to get a list of the machine state names (and yes, you're correct the ACSP registers are described in teh Arm procedure call standard) - however, not matching 'any' disassembly view I could think of. 

That's not the problem - as for ARM32, I could just use the `alias_names` to get those. However, that does not work for e.g. ARM64. For ARM64, X86, X64 - I could use simply `register.name`. The point is, it's not generically. 

So in my opinion - be it alias_names, be it name or something new - the general_purpose registers (or default_symbolic_registers) should have a way to get the machine register names, or in this case let's respell it to "commonly displayed register names by disassemblers such as capstone, ida, hopper, ..). And with this new update, a generic way to go for this is missing. 

Not a huge problem, or better - not a problem in the definition of a problem/bug in any way. More just a visualization problem. Never used angr_management, but can imagine when visualizing a state - compared to a capstone block might have the same strange touch to it when having to translate r0 to a1 and so on.

**Comment by tyb0807** [comment]
> So in my opinion - be it alias_names, be it name or something new - the general_purpose registers (or default_symbolic_registers) should have a way to get the machine register names
This is exactly where komasa and fish do not agree: they want to have semantic names in the general purpose registers list.

I agree that the semantic names are not really used by disassemblers. But maybe there might be some options which let us choose the register names to be used? As you can see, `capstone` itself is not consistent: `pc` is a semantic name, it should be `r15` if you really want to use `r0-r15` naming scheme.

**Comment by rhelmot** [comment]
For the sake of simplicity let's change things back to the way they were before. Right now archinfo is in a weird transitional state and we'll have to break some APIs in order to get it to the place it needs to be. Notably, we're trying to move away from a VEX offset being the identifying characteristic, so like we should eventually make `arch.registers` be a mapping from name to Register instance.

In the meantime, the "customizability" can be making your own Arch instance that has Registers with the names that you prefer. By passing this to the base project it'll propagate to literally everything else in angr.

**Comment by rhelmot** [comment]
I merged the associated PR, reverted the associated angrop change, and switched the alias names to the semantic names, which the PR forgot to do :P
