### ISSUE TITLE
KeyError: 'ip' during import

### ISSUE THREAD

**Issue by xorond** [angr/archinfo#50]
```
Python 3.7.1 (default, Oct 22 2018, 10:41:28) 
[GCC 8.2.1 20180831] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import archinfo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/archinfo/__init__.py", line 12, in <module>
    from .arch_amd64    import ArchAMD64
  File "/usr/lib/python3.7/site-packages/archinfo/arch_amd64.py", line 252, in <module>
    register_arch([r'.*amd64|.*x64|.*x86_64|.*metapc'], 64, Endness.LE, ArchAMD64)
  File "/usr/lib/python3.7/site-packages/archinfo/arch.py", line 655, in register_arch
    all_arches.append(my_arch(endness))
  File "/usr/lib/python3.7/site-packages/archinfo/arch_amd64.py", line 33, in __init__
    super(ArchAMD64, self).__init__(endness)
  File "/usr/lib/python3.7/site-packages/archinfo/arch.py", line 211, in __init__
    self.ip_offset = self.registers['ip'][0]
KeyError: 'ip'
>>> 
```

any idea why this could be occuring? i've tried importing the other arches as well, all of them give me the same error.

**Comment by ltfish** [comment]
Does pyvex import for you?

**Comment by xorond** [comment]
it does. importing archinfo separately fails though.

**Comment by rhelmot** [comment]
Hm. The only thing I can think of that would cause that is either pyvex failing to import or the pyvex register-name mapping failing to compile correctly. Regardless, I've pushed 7df0278828ac0efc2f7c04dd5925ebe2a1b8906d which should fix this. I've confirmed archinfo still works when pyvex is installed.

**Comment by xorond** [comment]
hi. thanks! i packaged angr for archstrike so i had to test all the dependencies one by one. i guess archinfo isn't supposed to be imported standalone, since i could import angr or pyvex properly. thanks for the help anyway. everything works properly :)

**Comment by ltfish** [comment]
You should be able to import archinfo as a stand-alone package. Not sure what is going wrong...
