### ISSUE TITLE
MIPS64 and branch_delay_slots

### ISSUE THREAD

**Issue by HexRoman** [angr/archinfo#58]
I see that in `MIPS32`:
`branch_delay_slot = True`

However, this definition doesn't appear in `MIPS64`.
Is that in purpose?

**Comment by ltfish** [comment]
No. We’ve probably never analyzed MIPS64 binaries seriously.

**Comment by HexRoman** [comment]
Should I create a pull request to change it?

**Comment by rhelmot** [comment]
Yep!

**Comment by saullocarvalho** [comment]
This issue seems fixed.
https://github.com/angr/archinfo/blob/75c62c8c40b6635e555c23e85777cb74ef880fd0/archinfo/arch_mips64.py#L49-L51
